apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb2
  name: jvb2-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30301
    protocol: UDP
    targetPort: 30301
    nodePort: 30301
  selector:
    k8s-app: jitsi
